### ISSUE TITLE
Unable to run locally

### ISSUE THREAD

**Issue by canadaduane** [AnxiousDarkly/svelte-icons#30]
I followed the directions in the README and ran `yarn install` in project root as well as `example/` dir. Then ran `yarn dev` in project root, and in another terminal, `yarn dev` in `example/` dir.

When I load localhost:5000 I see the following error in the JS console (and a blank HTML page):

`Uncaught TypeError: Failed to resolve module specifier "svelte-icons/di/DiGithubAlt.svelte". Relative references must start with either "/", "./", or "../".`

Am I missing a step?

**Comment by guttenbergovitz** [comment]
Not sure if it is related somehow but got some issues after running dev on SvelteKit 7.1, while production build seems fine.

**Comment by AnxiousDarkly** [comment]
I haven't been able to reproduce this issue so I will close for now.
